### ISSUE TITLE
Define `βfunc(n::Int,u::H)` outside `solve!`

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/MultiPrecisionR2#28]
https://github.com/d-monnet/MultiPrecisionR2/blob/4d579a4bee6ac8b2f8df379baa53ea0b2c759802/src/MultiPrecisionR2.jl#L254

Maybe add the model as a 3rd argument of this function.

**Comment by d-monnet** [comment]
Fixed
